server:
  port: 8082

spring:
  datasource:
    url: # your database url
    username: #
    password: #
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: amqps://fwjxnbbf:t-WbMINGb0ZT_RV480E6NUotO7CAoocl@jackal.rmq.cloudamqp.com/fwjxnbbf
  mail:
    host: smtp.gmail.com
    port: 587
    username: # your email
    password: # your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: "smtp.gmail.com"
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
broker:
  queue:
    email:
      name: default.email
