server:
  port: 8081

spring:
  datasource:
    url: # your database url
    username: #
    password: #
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: amqps://fwjxnbbf:t-WbMINGb0ZT_RV480E6NUotO7CAoocl@jackal.rmq.cloudamqp.com/fwjxnbbf
broker:
  exchange:
    name: fanout.exchange
  queue:
    email:
      name: default.email
    log:
      name: log.queue