server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/micro_email
    username: UserJava
    password: JavaTestMicro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    addresses: amqps://fwjxnbbf:t-WbMINGb0ZT_RV480E6NUotO7CAoocl@jackal.rmq.cloudamqp.com/fwjxnbbf
broker:
  queue:
    log:
      name: log.queue
